from core.base_enum import BaseEnum


class States(BaseEnum):
    START = 'START'
    GET_NAME = 'GET_NAME'
    GET_USERNAME = 'GET_USERNAME'
    GET_TASK_TITLE = 'GET_TASK_TITLE'
    GET_TASK_DESCRIPTION = 'GET_TASK_DESCRIPTION'
    MARK_TASK_COMPLETED = 'MARK_TASK_COMPLETED'
    DELETE_TASK = 'DELETE_TASK'
